DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS BOOK(
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  AUTHOR VARCHAR(64) NOT NULL,
  ISBN ISBN,
  RATING INT CHECK(RATING>=0 AND RATING<=10),
  RELEASE_DATE DATE,
  PUBLISHER VARCHAR(64)
);

INSERT INTO BOOK (TITLE,AUTHOR,ISBN,RATING,RELEASE_DATE,PUBLISHER) VALUES
('Pisma ascetyczne. T.1','Ewagriusz z Pontu','9788373541795',10,'2012-08-17','Wydawnictwo Benedyktynów Tyniec');
