CREATE TABLE IF NOT EXISTS PUBLISHER(
  ID_PUBLISHER SERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHOR(
  ID_AUTHOR SERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  SURNAME VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE(
  ID_GENRE SERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL
);

CREATE TABLE BOOK IF NOT EXISTS BOOK(
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  ISBN CHAR(13) NOT NULL UNIQUE CHECK(LEN(ISBN)==13),
  READ BOOLEAN NOT NULL,
  DESCRIPTION TEXT,
  COMMENTS TEXT,
  PRICE REAL CHECK(PRICE>0),
  REALASE_DATE DATE,
  BOOKMARK TEXT,
  
